name: Copy Folder to Design System Repo

on: workflow_dispatch

jobs:
  copy-files-to-mono-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          repository: tanishrajkumar/design-tokens
          path: design-tokens

      - name: Check out target repository
        uses: actions/checkout@v3
        with:
          repository: tanishrajkumar/design-system
          path: design-system
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Copy folder
        run: |
          directory="design-system/scss"
          if [ ! -d "$directory" ]; then
              mkdir -p "$directory"
          fi
          cp -r design-tokens/build/** design-system/scss
          cd design-system
          a=$(ls -l)
          echo "${a[0]}"

      # - name: Set up Git user and create PR
      #   working-directory: design-system
      #   run: |
      #     chmod +x .github/workflows/create-pr.sh
      #     bash .github/workflows/create-pr.sh
      #   env:
      #     GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     GH_USER_NAME: tanishrajkumar
      #     GH_USER_EMAIL: tanishraj.k@bsfdv.com
      #     NEW_FEATURE_BRANCH: "feat/style-dictionary"
      #     PR_TITLE: "feat: Replacing the style tokens"
      #     PR_BODY: "Replacing the style tokens as figma tokens have changed."
      #     PR_AUTO_MERGE: "false"
      #     WORKING_REPO: "design-system"

      # - name: Commit and push changes
      #   working-directory: design-system
      #   run: |
      #     git config --global user.name "tanishrajkumar"
      #     git config --global user.email "tanishraj.k@bsfdv.com"
      #     git add .
      #     git commit -m "Copy folder from source repository"
      #     git push
