name: Copy Folder to Design System Repo

on: workflow_dispatch

jobs:
  copy-files-to-mono-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          repository: tanishrajkumar/design-tokens
          path: design-tokens

      - name: Check out target repository
        uses: actions/checkout@v2
        with:
          repository: tanishrajkumar/design-system
          path: design-system
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Copy folder
        run: |
          cp -r design-tokens/build design-system

      - name: Commit and push changes
        working-directory: design-system
        run: |
          git config --global user.name "tanishrajkumar"
          git config --global user.email "tanishraj.k@bsfdv.com"
          git add .
          git commit -m "Copy folder from source repository"
          git push
