name: Copy Folder to Design System Repo

on: workflow_dispatch

jobs:
  copy-files-to-mono-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          repository: tanishrajkumar/design-tokens
          path: design-tokens

      - name: Check out target repository
        uses: actions/checkout@v3
        with:
          repository: tanishrajkumar/design-system
          path: design-system
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Copy folder and create PR
        run: |
          directory="design-system/scss"
          if [ ! -d "$directory" ]; then
              mkdir -p "$directory"
          fi
          cp -r design-tokens/build/** design-system/scss
          cd design-system

          git config --global user.name "tanishrajkumar"
          git config --global user.email "tanishraj.k@bsfdv.com"
          NEW_BRANCH_NAME="copy-folder"

          git checkout $NEW_BRANCH_NAME
          git add .
          git commit -m "Copy folder from source repository"
          git push origin $NEW_BRANCH_NAME
          echo ${{ secrets.REPO_ACCESS_TOKEN }} | gh auth login --with-token
          PR_TITLE="Copy folder from source repository"
          PR_BODY="This PR adds a folder from the source repository."
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $NEW_BRANCH_NAME
