name: Design Tokens Workflow

on: push

jobs:
  install_package_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node modules
        run: npm install

      - name: Run npm command
        run: npm run build

      - name: Commit and Push and Create PR
        uses: golfzaptw/action-commit-push-pr@1.0.2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PREFIX_BRANCHES: "update"
          DEFAULT_BRANCHES: "main"
          COMMIT_MESSAGE: "update value"
          TITLE_PR: "Design Tokens Updated Values"
          BODY_PR: "Design token has been changed."
