name: Figma Design Tokens Workflow

on:
  push:
    paths:
      - "tokens/**/*.json"

jobs:
  install_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run npm command
        run: npm run dictionary
