name: Design Tokens Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - "tokens/**"

jobs:
  install_package_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run npm command
        run: npm run build

      - name: Get commit message
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          COMMIT_MESSAGE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} | jq -r '.commit.message')

      - name: Set up Git user and create PR
        run: |
          chmod +x .github/workflows/create-pr.sh
          bash .github/workflows/create-pr.sh
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          PR_TITLE: $COMMIT_MESSAGE
          GH_USER_NAME: tanishrajkumar
          GH_USER_EMAIL: tanishraj.k@bsfdv.com

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: install_package_and_build
    steps:
      - name: Workflow Status
        run: |
          if [ "${{ needs.install_package_and_build.result }}" == "success" ]; then
            echo "SLACK_MESSAGE=Build succeeded" >> $GITHUB_ENV
          else
            echo "SLACK_MESSAGE=Build failed" >> $GITHUB_ENV
          fi

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
