name: Figma Design Tokens Workflow

on:
  workflow_dispatch:

jobs:
  install_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node modules
        run: npm install

      - name: Run npm command
        run: npm run build
