name: Design Tokens Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - figma_tokens
      - main

jobs:
  install_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run npm command
        run: npm run build

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create new branch
        run: |
          git checkout -b new-feature-branch
          git add .
          git commit -m "Add new changes"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin new-feature-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          title: "New changes"
          body: "This PR includes new changes."
          branch: "new-feature-branch"
          base: "main"
