name: Figma Design Tokens Workflow

on:
  push:
    paths:
      - "tokens/**/*.json"

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "A JSON file has been changed"
