name: Figma Design Tokens Workflow

on:
  workflow_dispatch:

jobs:
  install_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node modules
        run: npm install

      - name: Run npm command
        run: npm run build

      - name: Configure Git
        run: |
          git config user.email "tanishraj.k@bsfdv.com"
          git config user.name "tanishrajkumar"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated build"

      - name: Push changes to branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
