name: Design Tokens Workflow

on: push

jobs:
  install_package_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node modules
        run: npm install

      - name: Run npm command
        run: npm run build
